name: Deploy Backend to VPS

on:
  push:
    branches:
      - main # Chạy khi có push vào branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.VPS_PATH }}
            git pull origin main
            cd backend
            npm install --production
            pm2 restart ${{ secrets.PM2_NAME }} || pm2 start src/server.js --name "${{ secrets.PM2_NAME }}"
